// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

// Name: Collection
export const Collection = z.object({
  // Name: Collection.id
  "id": z.string(),
  // Name: Collection.title
  "title": z.string(),
});
export type Collection = z.infer<typeof Collection>;

// Name: CollectionImage
export const CollectionImage = z.object({
  // Name: CollectionImage.collectionId
  "collectionId": z.string(),
  // Name: CollectionImage.hash
  "hash": z.string(),
  // Name: CollectionImage.filename
  "filename": z.string(),
  // Name: CollectionImage.url
  "url": z.string(),
});
export type CollectionImage = z.infer<typeof CollectionImage>;

// Name: CreateCollection
export const CreateCollection = z.object({
  // Name: CreateCollection.id
  "id": z.string(),
});
export type CreateCollection = z.infer<typeof CreateCollection>;

// Name: CreateCollectionBody
export const CreateCollectionBody = z.object({
  // Name: CreateCollectionBody.title
  "title": z.string(),
});
export type CreateCollectionBody = z.infer<typeof CreateCollectionBody>;

// Name: EditCollectionBody
export const EditCollectionBody = z.object({
  // Name: EditCollectionBody.title
  "title": z.string().nullable().optional(),
});
export type EditCollectionBody = z.infer<typeof EditCollectionBody>;

// Name: Page
export const Page = z.object({
  // Name: Page.page
  "page": z.number(),
  // Name: Page.perPage
  "perPage": z.number(),
  // Name: Page.totalItems
  "totalItems": z.number(),
  // Name: Page.totalPages
  "totalPages": z.number(),
});
export type Page = z.infer<typeof Page>;

// Name: GetCollection
export const GetCollection = z.object({
  // Name: GetCollection.page
  "page": Page,
  // Name: GetCollection.collections
  "collections": z.array(Collection),
});
export type GetCollection = z.infer<typeof GetCollection>;

// Name: GetCollectionById
export const GetCollectionById = z.object({
  // Name: GetCollectionById.id
  "id": z.string(),
  // Name: GetCollectionById.title
  "title": z.string(),
});
export type GetCollectionById = z.infer<typeof GetCollectionById>;

// Name: GetCollectionImages
export const GetCollectionImages = z.object({
  // Name: GetCollectionImages.images
  "images": z.array(CollectionImage),
});
export type GetCollectionImages = z.infer<typeof GetCollectionImages>;

// Name: GetSystemInfo
export const GetSystemInfo = z.object({
  // Name: GetSystemInfo.version
  "version": z.string(),
});
export type GetSystemInfo = z.infer<typeof GetSystemInfo>;

// Name: Signin
export const Signin = z.object({
  // Name: Signin.token
  "token": z.string(),
});
export type Signin = z.infer<typeof Signin>;

// Name: SigninBody
export const SigninBody = z.object({
  // Name: SigninBody.password
  "password": z.string(),
});
export type SigninBody = z.infer<typeof SigninBody>;

